version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: orders-products-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: orders-products-backend
    depends_on:
      - mongodb
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/orders-products
      - SEED_DB=true
    ports:
      - "4000:4000"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: orders-products-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: